### PR TITLE
Update proposals - part 2

### PR DESCRIPTION
**Pull request by adblock-filters**
__________________________
**# 75**
[party.pl - zalando](https://party.pl/reklama/)
**REMOVED**
30e1125 - fixed by cbb9d27

__________________________
**# 76**
[party.pl - ecomm](https://party.pl/newsy/marta-manowska-komentuje-udzial-niny-w-the-voice-senior-9197-r22/)
69ade90
2019-08-25_12h07_51

__________________________
**# 77**
[firma.egospodarka.pl](http://www.firma.egospodarka.pl/raporty-o-firmach/firma,21311712,krzysztof-mimiec-best-food.html)
**REMOVED**
08e1d2d - fixed by dc24599

__________________________
**# 78**
[cooltura24.co](https://www.cooltura24.co.uk/)
45bab4c
2019-08-25_12h11_20

__________________________
**# 79**
[lokalna24.pl](https://www.lokalna24.pl/)
**REMOVED**
5f6c3a0 - fixed by e42521c

__________________________
**# 80**
[zdrowybialystok.pl](http://www.zdrowybialystok.pl/kuchnia.html)
**FIXED**
eece63c
2019-08-25_12h13_10

__________________________
**# 81**
[podlaskieagro.pl](http://podlaskieagro.pl)
99e1098 + fix cc418bf
2019-08-25_12h14_18

__________________________
**# 82**
[nieruchomoscipodlaskie.pl](http://www.nieruchomoscipodlaskie.pl/)
ec57adc
2019-08-25_12h14_56

__________________________
**# 83**
[kramik.pl](http://kramik.pl/)
88fef9d
2019-08-25_12h15_38

__________________________
**# 84**
[kantorywalut.pl](http://www.kantorywalut.pl/transfery-pieniezne/)
ea6735b
2019-08-25_12h15_55
2019-08-25_12h16_13

__________________________
**# 85**
[forum.bitcoin.pl](https://forum.bitcoin.pl/index.php )
5b46566
2019-08-25_12h16_35

__________________________
**# 86**
[kryptoportal.pl - hide](https://www.kryptoportal.pl)
9c144f4 - fixed by 0cae2d4
2019-08-25_12h17_18

__________________________
**# 87**
[kryptonotowania.pl - hide](http://www.kryptonotowania.pl/)
3e7797b
2019-08-25_12h17_47

__________________________
**# 88**
[kryptoportal.pl - block](https://www.kryptoportal.pl/kryptowaluty/ethereum/)
**REMOVED**
54fef03 - fixed by 0cae2d4

__________________________
**# 89**
[kucharze.pl](http://www.kucharze.pl/)
a016369 - fixed by 9d07990
2019-08-25_12h20_04

__________________________
**# 90**
[pepe-tv.eu](https://www.pepe-tv.eu/)
58a6d5b - fixed by a506aad
2019-08-25_12h23_52

__________________________
**# 91**
[oto-samochody.pl](https://www.oto-samochody.pl/)
d1616d9
2019-08-25_12h29_48

__________________________
**# 92**
[polskibiznes.info](https://www.polskibiznes.info/)
[pewnybiznes.info](https://www.pewnybiznes.info/)
**REMOVED**
37d979b - fixed by a810813

__________________________
**# 93**
[lwowecki.info](https://lwowecki.info/)
e0be504 - fixed by d82592d
2019-08-25_12h40_13

__________________________
**# 94**
[kariera24.info](https://www.kariera24.info/)
[and some sites from BlackHoodPress](https://www.blackhood.pl/index.php?route=product/category&path=59)
271834e
2019-08-25_12h41_48

__________________________
**# 95**
[piotrkowski24.pl](https://www.piotrkowski24.pl/)
e40a2a0 - fixed by 9b78217
2019-08-25_12h49_52

__________________________
**# 97**
[q4.pl](https://q4.pl/)
**REMOVED**
d381203 - fixed by 30aaf77

__________________________
**# 98**
[rowery.org](https://rowery.org/)
bd9334e
2019-08-25_13h03_36

__________________________
**# 99**
[goal.pl](https://www.goal.pl/)
[primeradivision.pl](https://www.primeradivision.pl/)
[eredivisie.pl](https://www.eredivisie.pl/)
[ligapolska.pl](https://www.ligapolska.pl/)
[seriea.pl](https://www.seriea.pl/)
2307d3e - fixed by 8de9519
2019-08-25_13h08_07
2019-10-19_13h34_21

__________________________
**# 100**
[eredivisie.pl](https://www.eredivisie.pl/)
[goal.pl](https://www.goal.pl/)
[primeradivision.pl](https://www.primeradivision.pl/)
[kadra.pl](https://www.kadra.pl/)
[ligapolska.pl](https://www.ligapolska.pl/)
[seriea.pl](https://www.seriea.pl/)
309b218
2019-08-25_13h12_20

__________________________
**# 102**
[pilkarskieforum.com](http://pilkarskieforum.com/)
**REMOVED**
f8cce4a - fixed by 630ebf0

__________________________
**# 103**
[glos.live](https://glos.live/)
f28a921
2019-09-05_11h36_27

__________________________
**# 104**
[gwint24.pl](https://gwint24.pl/)
fc7a107
2019-09-05_11h37_29

__________________________
**# 105**
[forbot.pl](https://forbot.pl/blog/czy-kolejnosc-w-polaczeniu-szeregowym-ma-znaczenie-id16788)
39584ad
2019-09-05_11h50_30
2019-09-05_11h50_40

__________________________
**# 106**
[sprowadzanie-aut.pl](https://sprowadzanie-aut.pl/import-aut/)
e6dbd10 - fixed by 15b8e0e
2019-09-06_11h20_41

__________________________
**# 107**
[kariera24.info](https://www.kariera24.info/)
[and some sites from BlackHoodPress](https://www.blackhood.pl/index.php?route=product/category&path=59)
890fc40 - fixed by a810813
2019-09-06_11h20_46

__________________________
**# 108**
[tromil.pl - script](https://tromil.pl/)
[tromil.pl](https://tromil.pl/poradniki-elektroniczne/diagnostyka-naprawa-monitorow-lcd/)
c715167 - fixed by b8842f7
2019-09-06_11h22_50
2019-10-19_14h06_07

__________________________
**# 109**
[tromil.pl](https://tromil.pl/drukarka-kserokopiarka-co-wybrac/)
c601ce6
2019-09-06_11h30_38

__________________________
**# 110**
[meczenazywo.pl](https://www.meczenazywo.pl/analiza-meczu/eliminacje-mistrzostw-europy/slowenia-polska/204377)
**REMOVED**
97af138 - fixed by 59c787f

__________________________
**# 111**
[mecze24.pl](https://www.mecze24.pl/tenis/turniej-atp-challenger-w-portoroz)
**REMOVED**
10b97c2 - fixed by 59c787f

__________________________
**# 112**
[mgsm.pl](https://www.mgsm.pl/pl/)
c58f172 - fixed by f7221ee
2019-09-06_11h36_59

__________________________
**# 113**
[mgsm.pl - div](https://www.mgsm.pl/pl/katalog/samsung/galaxysiii/test/675/To-co-tygrysy-lubi%C4%85-najbardziej.html)
**REMOVED**
d228f42 - fixed by f7221ee

__________________________
**# 114**
[miedziak.info.pl](http://miedziak.info.pl/)
[tutajlegnica.pll](http://tutajlegnica.pl)
b481492 - fixed by 9485ad5
2019-09-06_11h45_06

__________________________
**# 115**
[obud.pl](http://www.obud.pl/)
[chemiabudowlana.info](http://www.chemiabudowlana.info/)
eb56445
2019-09-06_11h46_43

__________________________
**# 116**
[chemiabudowlana.info](http://www.chemiabudowlana.info/)
[obud.pl](http://www.obud.pl/)
43a92e8 - fixed by 40c14bd
2019-09-06_11h46_51

__________________________
**# 117**
[ok24.tv](http://ok24.tv/)
8368d9b
2019-09-06_11h52_15

__________________________
**# 118**
[okraglemiasto.pl](https://okraglemiasto.pl/)
3bfda06 - fixed by afcc270
2019-09-06_12h05_14

__________________________
**# 119**
[okraglemiasto.pl](https://okraglemiasto.pl/wartaki-z-dotacji-zakupily-instrumenty-muzyczne/)
0d092e6
2019-09-06_12h01_52

__________________________
**# 120**
[gospodarka.dziennik.pl](https://gospodarka.dziennik.pl/news/artykuly/603994,ukraina-marcin-swiecicki-rzecznik-przedsiebiorcy-prezydent-warszawa.html)
**REMOVED**
fa2bbd1 - fixed by 9cead89

__________________________
**# 122**
[trakt.tv](https://trakt.tv/movies/the-lion-king-2019)
cb28c50
2019-09-06_12h21_29

__________________________
**# 123**
[zegarkiipasja.pl](https://zegarkiipasja.pl/)
70b9ee8 - fixed by 09582a9
2019-09-06_12h26_42

__________________________
**# 124**
[centrumdruku3d.pl - hp](http://centrumdruku3d.pl/instalacja-hp-jet-fusion-3d-580-color-do-profesjonalnego-druku-3d-w-krakowskim-centrum-druku/)
2c3a57f - fixed by 643b0b4
2019-09-06_12h30_11

__________________________
**# 125**
[centrumdruku3d.pl - hide](http://centrumdruku3d.pl/)
68f931c - fixed by 643b0b4
2019-09-06_12h30_27

__________________________
**# 126**
[elektroda.pl](https://www.elektroda.pl)
5b2adfe 
- fixed by e68d0a8
2019-09-06_12h37_10
2019-10-20_00h11_01

__________________________
**# *
23870fa - remove filters picked from pull #119 #120 - too generic or obsolete ones

### CODE REVIEW

**Comment by easylistpolish** [comment]
#75 
I can't reproduce
#76 
Good filter:)
#77 
Can't reproduce
#78 
Good filter
#79 
Too generic
^wysiwig^ is blocking also logo of the page and "ogloszenia lokalne" you would need also another whitelisting filter or change blocking one
#80
Good filter

**Comment by adblock-filters** [comment]
suggested fixes from pulls #119 #120 and
suggested fixes for filters # 75 - # 80 from this pull request applied

**Comment by easylistpolish** [comment]
Fixy
https://github.com/easylistpolish/easylistpolish/pull/127/commits/1e53f80db8ac1e2b8fc93d43814bfb98851caa0a
Zbyt generic. Blokuje też baner "rozmowy w oczekiwalni" 
Zamiast tego można
`anywhere.pl##a[data-track]`

https://github.com/easylistpolish/easylistpolish/pull/127/commits/42e5466912484293c90b91f57a253dd127c9c3b5
Banery na dole to są wydarzenia organizowane przez automotivesuppliers.pl
i niepotrzebna pusta linia na dole

https://github.com/easylistpolish/easylistpolish/pull/127/commits/8c06f15511969d790039632096b507d21c6c9ba3
Wygląda, że już nie potrzebny

https://github.com/easylistpolish/easylistpolish/pull/127/commits/8b7c026cecfd22513282d9fe3436994c05306127
`^banner^$domain=pless-intermedia.pl`
blokuje też zdjęcia do niektórych artykułów
`^rotator^$domain=pless-intermedia.pl`
z domeny pless-intermedia.pl są ściągane te zasoby, ale w opcji domain powinny być domeny, które je pobierają. Do tego już jest filtr `^rotator^$domain=(...)`, więc wystarczy dodać je tam:)

https://github.com/easylistpolish/easylistpolish/pull/127/commits/50e211adacef7277046c00888de6f11d61619db2
Shoperia jest częscią grupy interia, więc powinno zostać

Pozostałe filtry postaram się w przyszłym tygodniu sprawdzić:)

**Comment by easylistpolish** [comment]
99e1098 + fix cc418bf
ec57adc
ok

88fef9d
reklama po lewej to autopromocja zmieniłbym filtr na 
`kramik.pl##a[href^="/glowna/reklama/"] > img[alt^="http"]`

ea6735b
5b46566
9c144f4 - fixed by 0cae2d4
54fef03 - fixed by 0cae2d4
3e7797b
a016369 - fixed by 9d07990
ok

**Comment by easylistpolish** [comment]
58a6d5b - fixed by a506aad
ok

d1616d9
tego filtra bym nie dodawał. Jest to podobny portal, nie widać mechanizmów śledzenia, więc może zwyczajnie polecają ten portal. Tak czy siak u góry jest kilka reklam, które nie są zablokowane

37d979b - fixed by a810813
ok, propozycja małej zmiany fix'a poniżej.

e0be504 - fixed by d82592d
dodałbym 
`lwowecki.info##.td-all-devices2`
jeżeli zmienią reklamy to i tak zostaną ukryte

271834e
e40a2a0 - fixed by 9b78217
d381203 - fixed by 30aaf77
bd9334e
ok

2307d3e - fixed by 8de9519
309b218
dodałbym
`goal.pl,primeradivision.pl,kadra.pl,ligapolska.pl,seriea.pl,eredivisie.pl##a[style*="background: url(https://www.goal.pl/ban/sts/"]`
bo link zostaje, mimo że tapety już nie ma
i zmieniłbym 
`goal.pl,primeradivision.pl,kadra.pl,ligapolska.pl,seriea.pl,eredivisie.pl###promoBannerPage > .reklamaNapis + center
goal.pl,primeradivision.pl,kadra.pl,ligapolska.pl,seriea.pl,eredivisie.pl###promoBanner`
na
`goal.pl,primeradivision.pl,kadra.pl,ligapolska.pl,seriea.pl,eredivisie.pl##.reklamaNapis + *
goal.pl,primeradivision.pl,kadra.pl,ligapolska.pl,seriea.pl,eredivisie.pl##.reklamaNapis`

f8cce4a - fixed by 630ebf0
ok

f28a921
dodałbym
`glos.live##.banner`
jakby zmienili linki

fc7a107
dodałbym
`gwint24.pl##.herald-txt-module`

39584ad
ok

e6dbd10 - fixed by 15b8e0e
zostawiłbym obydwa filtry.
Jeżeli reklamę można zablokować tylko poprzez specyficzny adres obrazka, a element html jest specyficzny tylko dla reklam to lepiej dodać obydwa filtry. Póki jest ta reklama, filtr blokujący przyśpieszy ładowanie strony i oszczędzi transfer użytkownikowi, a hiding filtr się przyda, bo za miesiąc mogą zmienić tą reklamę

890fc40 - fixed by a810813
zamieniłbym:
`||rankomat.pl/tracking^$image,domain=~rankomat.pl`
na:
`||partner.rankomat.pl/tracking/media^$image,third-party`
teoretycznie mogli by używać jakiegoś tracking pixel, żeby robić np. rankingi stron, więc zrobiłbym filtr bardziej specyficzny

**Comment by adblock-filters** [comment]
poprawione według propozycji z komentarzy powyżej

**Comment by easylistpolish** [comment]
c715167 - fixed by b8842f7
dodałbym
`tromil.pl##.rotator-ceneo`

c601ce6
c58f172 - fixed by f7221ee
b481492 - fixed by 9485ad5
ok

eb56445
Zamieniłbym
`||nevicom.pl/banery^$image,domain=obud.pl|chemiabudowlana.info`
na
`||nevicom.pl/wyswietl_baner.$script,third-party`

43a92e8 - fixed by 40c14bd
Zamieniłbym:
`||chemiabudowlana.info^*^25-kreisel-250.`
na
`||chemiabudowlana.info/banery^$image`

8368d9b
ok

3bfda06 - fixed by afcc270
Zamieniłbym te wszystkie filtry na:
`okraglemiasto.pl##.wpb_left-to-right`
`okraglemiasto.pl##.reklama_top`
Wygląda na to, że dość często zmieniają reklamy, a jak zablokujesz pojedynczy obrazek ze slidera to pojawia się i znika zamiać przewijać reklamy, więc w tym przypadku lepiej po prostu ukryć. Na dole jest slider tylko z autopromocją, więc nie dodawałbym w ogóle filtrów blokujących, gdyby tam wstawili jedną z tych reklam, żeby nie pogorszyć odbioru strony przez użytkowników, zamiast polepszyć

cb28c50
Zamieniłbym na
`#hu-ck-ster-desk-top-wrapper`
żeby ukryć też napis "hide ads with VIP"

70b9ee8 - fixed by 09582a9
Zamieniłbym:
`^banery_prawa^$domain=zegarkiipasja.pl`
na
`^banery_$domain=zegarkiipasja.pl`
i dodał
`zegarkiipasja.pl##.clickable-box-new-window[data-url^="http"]`

2c3a57f - fixed by 643b0b4
68f931c - fixed by 643b0b4
Wygląda na to, że zamienili
`||centrumdruku3d.pl^*^FORM3.`
na
`||centrumdruku3d.pl^*^METHODX.`

5b2adfe fixed by e68d0a8
ok:)

**Comment by adblock-filters** [comment]
poprawione według propozycji

**Pull request merged**
